apiVersion: v2
name: example-service-b
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
annotations:
  hypper.cattle.io/release-name: svc-b
  hypper.cattle.io/namespace: demo
  hypper.cattle.io/shared-dependencies: |
    - name: rancher-monitoring
      version: "^9.4.203"
      repository: "https://mattfarina.github.io/demo-hypper-charts/repo"
    - name: rancher-logging
      version: "^3.9.400"
      repository: "https://mattfarina.github.io/demo-hypper-charts/repo"
