apiVersion: v2
name: demo-b
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
annotations:
  hypper.cattle.io/release-name: demo-b
  hypper.cattle.io/namespace: demo-b