apiVersion: v2
name: demo-b
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
annotations:
  hypper.cattle.io/release-name: demo-b
  hypper.cattle.io/namespace: demo-b
  hypper.cattle.io/shared-dependencies: |
    - name: demo-c
      version: "^1.0.0"
      repository: "https://mattfarina.github.io/demo-hypper-charts/repo"
